# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6477aec05df03c761d7afc6c8fdf7854f4eb6102a6643130a397d8b691c3fbdcb0cddafb2eb2c1e960435a5b6677af15c0ec7698eb261210e8c3bd9f26ff8878

test:
  secret_key_base: a59b8b1df73abe4c63e31cf1d8c30049b99a18b1031daba77361cd29d2331bd36be147fbda1135dc283b02c9a344bc69a54a506a38eb4a1ca97f3ed68e07af1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
